---
- name: Install metricbeat
  hosts: webservers
  become: true
  tasks:
    # Use command to download metricbeat
    - name: Download metricbeat
      command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb

    # Use command to install metricbeat
    - name: Install metricbeat
      command: dpkg -i metricbeat-7.4.0-amd64.deb

    # Use copy to copy config information
    - name: Copy metribeat config file
      copy:
        src: /etc/ansible/files/metricbeat-config.yml
        dest: /etc/metricbeat/metricbeat.yml

    # Use command to enable and configure module
    - name: Enable and configure docker module for metricbeat
      command: metricbeat modules enable docker

    # Use command to setup metricbeat
    - name: Setup metricbeat
      command: metricbeat setup

    # Use command to start metricbeat
    - name: Start metricbeat
      command: service metricbeat start

    # Use systemd to enable on boot
    - name: Enable service metricbeat on boot
      systemd:
        name: metricbeat
        enabled: yes
